---
title: '2020-10-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
listExample <- list(student = "小明", 學期 = list(`108-1` = list(list(name = "個體經濟學", 
    teacher = "Alice", grade = 85)), `108-2` = list(list(name = "總體經濟學", 
    teacher = "Mark", grade = 78))))
# 有多少位置可選：
length(listExample)
listExample[[1]]
listExample[[2]]
listExample$student
listExample$學期  # 特殊命名依然要用反頓點呼叫
```
```{r}
vectorExample
vectorExample[c(1, 3)]
# 顯示到第一層
str(listExample, max.level = 1)

listExample[c(1, 2)]
```

```{r}
vectorExample <- c("小明", "小英", "大雄")

# 有多少位置可選：
length(vectorExample)
vectorExample[[1]]
vectorExample[[3]]
```

```{r}
listExample <- list(student = "小明", 學期 = list(`108-1` = list(list(name = "個體經濟學", 
    teacher = "Alice", grade = 85)), `108-2` = list(list(name = "總體經濟學", 
    teacher = "Mark", grade = 78))))
# 有多少位置可選：
length(listExample)
listExample[[1]]
listExample[[2]]
```
```{r}
# 有多少名字可選：
names(listExample)
listExample$student
listExample$學期  # 特殊命名依然要用反頓點呼叫
listExample[["student"]]
listExample$student

listExample[["學期"]]  # 小心不是反頓點喔。
listExample$學期
```
```{r}
vectorExample
vectorExample[c(1, 3)]
# 顯示到第一層
str(listExample, max.level = 1)

listExample[c(1, 2)]
```
```{r}
# 顯示到第一層
str(listExample, max.level = 1)

listExample[c("學期")]
listExample[c("student", "學期")]
```
```{r}
vectorExample
vectorExample[c(T, T, F)]  # 要，要，不要
str(listExample[c(F, T)])  # 不要，要
str(listExample[c(T, T)])  # 要，要
str(listExample)
```

```{r}
get1 <- listExample[["學期"]]
get2 <- listExample["學期"]
get1  # 學期拿出來，有3個元素的list
str(get1)
get2  # listExample 只留下 學期元素，是個只有一個元素的list
str(get2)
```

```{r}
numVector <- c(2, 3, 6, -1, 4, 2, 6)
select1 <- numVector[c(1, 4)]
select1
select2 <- select1[[1]]
select2

# 相當於
numVector[c(1, 4)][[1]]
select1 <- numVector[c(T, T, F, T, F, F, T)]
select1
select2 <- select1[c(1, 4)]
select2

# 相當於
numVector[c(T, T, F, T, F, F, T)][c(1, 4)]
```

```{r}
majors <- c("經濟學系", "經濟學系", "社會學系", "社工系", "經濟學系")
names <- c("小英", "小美", "大雄", "阿華", "阿尼")
gender <- c("F", "F", "M", "F", "M")
get1  # 學期拿出來，有3個元素的list
str(get1)
```

```{r}
today <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))
tomorrow <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))

weather <- list(today, tomorrow)

print(weather)

```

```{r}
weather[[1]][[2]][[2]]  # 今天/新北市/highest_temp
weather[[2]][[2]][[2]]  # 明天/新北市/highest_temp
```

```{r}
weather[[1]][[2]]$highest_temp  # 今天/新北市/highest_temp
weather[[2]][[2]]$highest_temp  # 明天/新北市/highest_temp
```

